apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: currency-converter
        image: cavanm/demo:currency-conversion
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 7863
        env:
        - name: REDIS
          value: "currency-converter"
---
apiVersion: v1
kind: Service
metadata:
  name: currency-converter
spec:
  type: NodePort
  ports:
  - port: 7863
  selector:
    app: currency-converter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: holidays
spec:
  replicas: 3
  selector:
    matchLabels:
      app: holidays
  template:
    metadata:
      labels:
        app: holidays
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: holidays
        image: cavanm/demo:holidays
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 7864
        env:
        - name: REDIS
          value: "holidays"
---
apiVersion: v1
kind: Service
metadata:
  name: holidays
spec:
  type: NodePort
  ports:
  - port: 7864
  selector:
    app: holidays
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tax-calculator
  template:
    metadata:
      labels:
        app: tax-calculator
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tax-calculator
        image: cavanm/demo:tax-calculator
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 7865
        env:
        - name: REDIS
          value: "tax-calculator"
---
apiVersion: v1
kind: Service
metadata:
  name: tax-calculator
spec:
  type: NodePort
  ports:
  - port: 7865
  selector:
    app: tax-calculator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servconnector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servconnector
  template:
    metadata:
      labels:
        app: servconnector
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: servconnector
        image: cavanm/demo:connector
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 7860
---
apiVersion: v1
kind: Service
metadata:
  name: servconnector
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: servconnector
